import { useLottie, useLottieInteractivity } from 'lottie-react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import hamsterAnimation from '../public/animations/hamster.json'
import { useState } from 'react'

export default function Home() {
  const [direction, setDirection] = useState<1 | -1>(1);
  const animation = useLottie({
    animationData: hamsterAnimation,
    loop: false,
    autoplay: false,
    onClick: () => handleClick(),
    style: { cursor: "pointer" }
  })

  // const interactiveAnimation = useLottieInteractivity({
  //   lottieObj: animation,
  //   mode: "cursor",
  //   actions: [
  //     {
  //       position: { x: [0, 1], y: [-1, 2] },
  //       type: "seek",
  //       frames: [-20, 60],
  //     },
  //     {
  //       position: { x: -4, y: -4 },
  //       type: "stop",
  //       frames: [0],
  //     },
  //   ],
  // });

  const handleClick = () => {
    animation.setDirection(direction)
    animation.play();
    setTimeout(() => {
      if (direction === 1) {
        setDirection(-1);
      } else {
        setDirection(1);
      }
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Lottie DevTalks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={direction === -1  ? styles.mainactive : styles.main}>
        <h1 className={styles.title}>
          Welcome to Lottie DevTalks
        </h1>
        {animation.View}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
