import { useLottie } from 'lottie-react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import hamsterAnimation from '../public/animations/hamster.json'
import { useState } from 'react'

export default function Home() {
  const [direction, setDirection] = useState<1 | -1>(1);
  const animation = useLottie({
    animationData: hamsterAnimation,
    loop: false,
    autoplay: false,
    onClick: () => handleClick(),
    style: { cursor: "pointer" }
  })

  const handleClick = () => {
    animation.setDirection(direction)
    animation.play();
    setTimeout(() => {
      if (direction === 1) {
        setDirection(-1);
      } else {
        setDirection(1);
      }
    }, animation.animationItem?.getDuration())
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Lottie DevTalks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={direction === -1  ? styles.mainactive : styles.main}>
        <h1 className={styles.title}>
          Welcome to Lottie DevTalks
        </h1>
        {animation.View}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
